- name: Checkout
  
- uses: actions/checkout@v2
  with:
    # Repository name with owner. For example, actions/checkout
    # Default: ${{ github.repository }}
    repository: 'antonkurenkov/systembuilder'
    ref: develop
