name: on-commit

on:
  push:
    branches:
      - develop

jobs:
  my-simple-job:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Unbelievable success!"
  
  job-checkout:
    runs-on: ubuntu latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        
