name: scheduler

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:

  my-simple-job:
    runs-on: ubuntu-latest
    steps:
        - run: echo "help"
  
  job-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
